let mupdf=null,hb=null,bidi=null,arabicFontData=null;
const $=id=>document.getElementById(id);
const fileInput=$('fileInput'),openBtn=$('openBtn'),engineState=$('engineState'),startScreen=$('startScreen'),app=$('app');
const fileName=$('fileName'),pageLabel=$('pageLabel'),viewer=$('viewer'),pageShell=$('pageShell'),pageCanvas=$('pageCanvas'),hitLayer=$('hitLayer'),editor=$('editor'),thumbs=$('thumbs');
const undoBtn=$('undoBtn'),redoBtn=$('redoBtn'),zoomOutBtn=$('zoomOutBtn'),zoomInBtn=$('zoomInBtn'),zoomLabel=$('zoomLabel'),fitBtn=$('fitBtn'),saveBtn=$('saveBtn');
const statusText=$('statusText'),fontText=$('fontText'),sizeText=$('sizeText'),langText=$('langText'),saveState=$('saveState');
let originalBytes=null,workingBytes=null,sourceName='',sourceDoc=null,workingDoc=null,pageIndex=0,pageCount=0,zoom=1,currentBounds=[0,0,595,842],sourceItems=[];
let edits=[],redoStack=[],activeItem=null,renderTicket=0,arabicPromise=null,editorBusy=false;
const dpr=()=>Math.min(3,window.devicePixelRatio||1);
const hasArabic=s=>/[\u0600-\u06FF\u0750-\u077F\u08A0-\u08FF\uFB50-\uFDFF\uFE70-\uFEFF]/.test(s||'');
const hasArabicLetters=s=>/[\p{Script=Arabic}]/u.test(String(s||'').replace(/[^\p{Letter}]/gu,''));
const dirOf=s=>hasArabicLetters(s)?'rtl':'ltr';
const cleanFont=s=>String(s||'').replace(/^[A-Z]{6}\+/,'').trim();
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const editKey=(p,b,t)=>`${p}|${b.map(v=>Number(v).toFixed(2)).join(',')}|${String(t).trim().slice(0,120)}`;

async function init(){try{engineState.textContent='جاري تحميل MuPDF…';mupdf=await import('https://cdn.jsdelivr.net/npm/mupdf@1.28.1/dist/mupdf.js');engineState.textContent='جاهز — اختر ملف PDF';openBtn.disabled=false;}catch(e){console.error(e);engineState.textContent='تعذر تحميل محرك PDF.';}}
init();openBtn.disabled=true;
openBtn.onclick=()=>fileInput.click();fileInput.onchange=async()=>{const f=fileInput.files?.[0];fileInput.value='';if(f)await openPDF(f);};

async function ensureArabic(){if(hb&&bidi&&arabicFontData)return;if(arabicPromise)return arabicPromise;arabicPromise=(async()=>{const [h,b,res]=await Promise.all([import('https://cdn.jsdelivr.net/npm/harfbuzzjs@1.6.1/dist/index.mjs'),import('https://cdn.jsdelivr.net/npm/bidi-js@1.1.0/dist/bidi.mjs'),fetch('https://raw.githubusercontent.com/google/fonts/main/ofl/notosansarabic/NotoSansArabic%5Bwdth%2Cwght%5D.ttf',{cache:'force-cache'})]);if(!res.ok)throw new Error('Arabic font load failed');hb=h;bidi=b.default();arabicFontData=await res.arrayBuffer();const face=new FontFace('Gradify Arabic',arabicFontData,{weight:'100 900'});await face.load();document.fonts.add(face);})();try{await arabicPromise}finally{arabicPromise=null;}}

function destroyDocs(){try{sourceDoc?.destroy?.()}catch{}try{workingDoc?.destroy?.()}catch{}sourceDoc=workingDoc=null;}
async function openPDF(file){try{statusText.textContent='فتح الملف…';originalBytes=new Uint8Array(await file.arrayBuffer());workingBytes=originalBytes.slice();sourceName=file.name;destroyDocs();sourceDoc=mupdf.Document.openDocument(originalBytes,'application/pdf');workingDoc=mupdf.Document.openDocument(workingBytes,'application/pdf');pageCount=sourceDoc.countPages();pageIndex=0;edits=[];redoStack=[];fileName.textContent=file.name;startScreen.hidden=true;app.hidden=false;await renderThumbnails();fitWidth();await renderPage();}catch(e){console.error(e);engineState.textContent='تعذر فتح الملف: '+(e.message||e);}}

function normBox(b){if(Array.isArray(b))return b.slice(0,4).map(Number);if(b&&typeof b==='object'&&'x0'in b)return[+b.x0,+b.y0,+b.x1,+b.y1];return null;}
function extractItems(page){let st=null;try{st=page.toStructuredText('preserve-spans,preserve-whitespace,accurate-bboxes,accurate-ascenders');const j=JSON.parse(st.asJSON()),out=[];for(const block of j.blocks||[]){if(block.type&&block.type!=='text')continue;for(const line of block.lines||[]){const text=String(line.text||'').trim(),bbox=normBox(line.bbox);if(!text||!bbox||bbox[2]<=bbox[0]||bbox[3]<=bbox[1])continue;const f=line.font||{};out.push({text,bbox,origin:[Number(line.x)||bbox[0],Number(line.y)||bbox[3]],fontName:cleanFont(f.name||''),family:f.family||'sans-serif',weight:f.weight||'normal',style:f.style||'normal',size:Number(f.size)||Math.max(7,(bbox[3]-bbox[1])*.8)});}}return out;}finally{try{st?.destroy?.()}catch{}}}
function getEdit(item){return edits.find(e=>e.key===editKey(pageIndex,item.bbox,item.text));}

async function renderPage(){if(!workingDoc)return;const ticket=++renderTicket;statusText.textContent='رندر عالي الدقة…';closeEditor(false);let wp=null,sp=null,pix=null;try{wp=workingDoc.loadPage(pageIndex);sp=sourceDoc.loadPage(pageIndex);currentBounds=wp.getBounds();sourceItems=extractItems(sp);const w=currentBounds[2]-currentBounds[0],h=currentBounds[3]-currentBounds[1],scale=zoom*dpr();pageShell.style.width=`${w*zoom}px`;pageShell.style.height=`${h*zoom}px`;pageCanvas.style.width=`${w*zoom}px`;pageCanvas.style.height=`${h*zoom}px`;pix=wp.toPixmap(mupdf.Matrix.scale(scale,scale),mupdf.ColorSpace.DeviceRGB,false,true,'View','CropBox');const blob=new Blob([pix.asPNG()],{type:'image/png'}),bmp=await createImageBitmap(blob);if(ticket!==renderTicket){bmp.close();return;}pageCanvas.width=bmp.width;pageCanvas.height=bmp.height;const ctx=pageCanvas.getContext('2d',{alpha:false});ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';ctx.clearRect(0,0,bmp.width,bmp.height);ctx.drawImage(bmp,0,0);bmp.close();renderHits();pageLabel.textContent=`الصفحة ${pageIndex+1} من ${pageCount}`;zoomLabel.textContent=`${Math.round(zoom*100)}%`;statusText.textContent='جاهز';document.querySelectorAll('.thumb').forEach((x,i)=>x.classList.toggle('active',i===pageIndex));}catch(e){console.error(e);statusText.textContent='خطأ في العرض: '+(e.message||e);}finally{try{pix?.destroy?.()}catch{}try{wp?.destroy?.()}catch{}try{sp?.destroy?.()}catch{}}}

function renderHits(){hitLayer.innerHTML='';for(const item of sourceItems){const b=item.bbox,el=document.createElement('div');el.className='hit';el.style.left=`${(b[0]-currentBounds[0])*zoom}px`;el.style.top=`${(b[1]-currentBounds[1])*zoom}px`;el.style.width=`${(b[2]-b[0])*zoom}px`;el.style.height=`${Math.max(4,(b[3]-b[1])*zoom)}px`;el.title=item.text;el.ondblclick=e=>{e.stopPropagation();openEditor(item,el)};hitLayer.appendChild(el);}}
function cssFont(item){const n=(item.fontName||'').toLowerCase();if(hasArabic(getEdit(item)?.newText??item.text))return '"Gradify Arabic","Segoe UI",Tahoma,Arial,sans-serif';if(n.includes('times')||item.family==='serif')return '"Times New Roman",serif';if(n.includes('courier')||item.family==='monospace')return 'Consolas,monospace';return 'Arial,"Segoe UI",sans-serif';}
function openEditor(item,hit){if(editorBusy)return;closeEditor(true);activeItem=item;const ed=getEdit(item),text=ed?.newText??item.text,b=item.bbox;document.querySelectorAll('.hit.active').forEach(x=>x.classList.remove('active'));hit.classList.add('active');editor.hidden=false;editor.textContent=text;editor.dir=dirOf(text);editor.style.textAlign=dirOf(text)==='rtl'?'right':'left';editor.style.fontFamily=cssFont(item);editor.style.fontWeight=item.weight||'normal';editor.style.fontStyle=item.style||'normal';editor.style.fontSize=`${Math.max(10,item.size*zoom)}px`;editor.style.left=`${(b[0]-currentBounds[0])*zoom}px`;editor.style.top=`${(b[1]-currentBounds[1])*zoom}px`;editor.style.width=`${Math.max(20,(b[2]-b[0])*zoom)}px`;editor.style.height=`${Math.max(18,(b[3]-b[1])*zoom*1.15)}px`;fontText.textContent=item.fontName||item.family||'—';sizeText.textContent=`${item.size.toFixed(1)} pt`;langText.textContent=hasArabic(text)?'العربية / RTL':'English / LTR';editor.focus();const r=document.createRange(),s=getSelection();r.selectNodeContents(editor);s.removeAllRanges();s.addRange(r);}
function editorValue(){return String(editor.textContent||'').replace(/\n/g,'');}
async function closeEditor(commit=true){if(!activeItem||editor.hidden)return;const item=activeItem,newText=editorValue(),key=editKey(pageIndex,item.bbox,item.text);editor.hidden=true;activeItem=null;document.querySelectorAll('.hit.active').forEach(x=>x.classList.remove('active'));if(commit&&newText!==item.text){const old=edits.map(x=>({...x,bbox:[...x.bbox],origin:[...x.origin]}));edits=edits.filter(e=>e.key!==key);edits.push({key,page:pageIndex,bbox:[...item.bbox],origin:[...item.origin],oldText:item.text,newText,fontSize:item.size,fontName:item.fontName,family:item.family,weight:item.weight,style:item.style});redoStack=[];editorBusy=true;statusText.textContent='تطبيق التعديل…';try{await rebuildWorking();await renderPage();}catch(e){console.error(e);edits=old;statusText.textContent='فشل التعديل: '+(e.message||e);}finally{editorBusy=false;updateHistoryButtons();}}}
document.addEventListener('mousedown',e=>{if(!editor.hidden&&!editor.contains(e.target)&&!e.target.classList.contains('hit'))void closeEditor(true);});editor.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();closeEditor(false)}if(e.key==='Enter'){e.preventDefault();editor.blur();void closeEditor(true)}});editor.addEventListener('input',()=>{editor.dir=dirOf(editorValue());editor.style.textAlign=editor.dir==='rtl'?'right':'left';});

function expand(r,p=.25){return[r[0]-p,r[1]-p,r[2]+p,r[3]+p];}
function daFont(e){if(e.family==='serif'||/times/i.test(e.fontName))return'TiRo';if(e.family==='monospace'||/courier/i.test(e.fontName))return'Cour';return'Helv';}
function weightVal(e){const s=`${e.weight||''} ${e.fontName||''}`.toLowerCase();return /bold|700|800|900/.test(s)?700:400;}
function visualRuns(text){if(!bidi)return[{text,direction:dirOf(text),level:dirOf(text)==='rtl'?1:0}];const emb=bidi.getEmbeddingLevels(text,dirOf(text)),levels=emb.levels,r=[];let st=0;for(let i=1;i<=text.length;i++)if(i===text.length||levels[i]!==levels[st]){r.push({text:text.slice(st,i),direction:levels[st]%2?'rtl':'ltr',level:levels[st]});st=i;}const max=Math.max(...r.map(x=>x.level)),odds=r.filter(x=>x.level%2).map(x=>x.level);if(odds.length)for(let l=max;l>=Math.min(...odds);l--)for(let i=0;i<r.length;){if(r[i].level<l){i++;continue}let j=i+1;while(j<r.length&&r[j].level>=l)j++;r.splice(i,j-i,...r.slice(i,j).reverse());i=j;}return r;}
function pathCommands(cmds,ox,oy,sc){let out='',cx=0,cy=0;const tr=(x,y)=>[ox+x*sc,oy+y*sc];for(const c of cmds){const t=String(c.type||'').toUpperCase(),v=c.values||[];if(t==='M'){[cx,cy]=tr(v[0],v[1]);out+=`${cx} ${cy} m\n`}else if(t==='L'){[cx,cy]=tr(v[0],v[1]);out+=`${cx} ${cy} l\n`}else if(t==='C'){const a=tr(v[0],v[1]),b=tr(v[2],v[3]),d=tr(v[4],v[5]);out+=`${a[0]} ${a[1]} ${b[0]} ${b[1]} ${d[0]} ${d[1]} c\n`;[cx,cy]=d}else if(t==='Q'){const q=tr(v[0],v[1]),p=tr(v[2],v[3]),c1=[cx+(q[0]-cx)*2/3,cy+(q[1]-cy)*2/3],c2=[p[0]+(q[0]-p[0])*2/3,p[1]+(q[1]-p[1])*2/3];out+=`${c1[0]} ${c1[1]} ${c2[0]} ${c2[1]} ${p[0]} ${p[1]} c\n`;[cx,cy]=p}else if(t==='Z')out+='h\n'}return out;}
function shape(font,text,direction){const buf=new hb.Buffer();buf.addText(text);try{buf.setDirection(direction==='rtl'?hb.Direction.RTL:hb.Direction.LTR)}catch{}buf.guessSegmentProperties();hb.shape(font,buf);const gs=buf.getGlyphInfosAndPositions(),out=[];let pen=0,minX=Infinity,maxX=-Infinity,minY=Infinity,maxY=-Infinity;for(const g of gs){const x=pen+(g.xOffset||0),y=g.yOffset||0,cmds=font.glyphToJson(g.codepoint)||[];for(const c of cmds){const v=c.values||[];for(let i=0;i+1<v.length;i+=2){minX=Math.min(minX,x+v[i]);maxX=Math.max(maxX,x+v[i]);minY=Math.min(minY,y+v[i+1]);maxY=Math.max(maxY,y+v[i+1]);}}out.push({x,y,cmds});pen+=g.xAdvance||0;}try{buf.destroy?.()}catch{}if(!isFinite(minX)){minX=minY=0;maxX=Math.max(1,pen);maxY=1000}return{glyphs:out,advance:pen,minX,maxX,minY,maxY};}
async function arabicAppearance(e){await ensureArabic();const blob=new hb.Blob(arabicFontData),face=new hb.Face(blob),font=new hb.Font(face);font.setScale(1000,1000);try{font.setVariations?.([new hb.Variation('wght',weightVal(e))])}catch{}const runs=visualRuns(e.newText).map(r=>({...r,sh:shape(font,r.text,r.direction)}));let x=0,minX=Infinity,maxX=-Infinity,minY=Infinity,maxY=-Infinity;for(const r of runs){r.off=x;minX=Math.min(minX,x+r.sh.minX);maxX=Math.max(maxX,x+r.sh.maxX);minY=Math.min(minY,r.sh.minY);maxY=Math.max(maxY,r.sh.maxY);x+=Math.max(0,r.sh.advance);}const bw=e.bbox[2]-e.bbox[0],bh=e.bbox[3]-e.bbox[1],rw=Math.max(1,maxX-minX),rh=Math.max(1,maxY-minY);let sc=(e.fontSize||bh)/1000;if(rh*sc>bh*1.05)sc*=bh/(rh*sc);if(rw*sc>bw*1.05)sc*=bw/(rw*sc);const xb=dirOf(e.newText)==='rtl'?bw-maxX*sc:-minX*sc,base=Array.isArray(e.origin)?bh-(e.origin[1]-e.bbox[1]):bh*.78,yb=clamp(base,-minY*sc,Math.max(-minY*sc,bh-maxY*sc));let content='q\n0 g\n';for(const r of runs)for(const g of r.sh.glyphs)content+=pathCommands(g.cmds,xb+(r.off+g.x)*sc,yb+g.y*sc,sc)+'f\n';content+='Q\n';try{font.destroy?.();face.destroy?.();blob.destroy?.()}catch{}return{content,bbox:[0,0,bw,bh]};}
async function addArabic(page,pdf,e){const ap=await arabicAppearance(e),a=page.createAnnotation('Stamp');a.setRect(e.bbox);a.setContents(e.newText);a.setAppearance('N',null,mupdf.Matrix.identity,ap.bbox,pdf.newDictionary(),ap.content);}

async function buildBytes(){if(edits.some(e=>hasArabic(e.newText)))await ensureArabic();let doc=null;try{doc=mupdf.Document.openDocument(originalBytes,'application/pdf');const pdf=typeof doc.asPDF==='function'?doc.asPDF():doc,groups=new Map();for(const e of edits){if(!groups.has(e.page))groups.set(e.page,[]);groups.get(e.page).push(e);}for(const [pi,list] of groups){const page=pdf.loadPage(pi);for(const e of list){const r=page.createAnnotation('Redaction');r.setRect(expand(e.bbox,.15));r.update?.();}page.applyRedactions(false,mupdf.PDFPage.REDACT_IMAGE_NONE,mupdf.PDFPage.REDACT_LINE_ART_NONE,mupdf.PDFPage.REDACT_TEXT_REMOVE);for(const e of list){if(!e.newText)continue;if(hasArabic(e.newText))await addArabic(page,pdf,e);else{const a=page.createAnnotation('FreeText');a.setRect(expand(e.bbox,.05));a.setContents(e.newText);a.setDefaultAppearance(daFont(e),e.fontSize,[0,0,0]);a.update();}}page.update?.();page.destroy?.();}const buf=pdf.saveToBuffer('compress');return new Uint8Array(buf.asUint8Array());}finally{try{doc?.destroy?.()}catch{}}}
async function rebuildWorking(){workingBytes=await buildBytes();try{workingDoc?.destroy?.()}catch{}workingDoc=mupdf.Document.openDocument(workingBytes,'application/pdf');saveState.textContent=`تم تجهيز ${edits.length} تعديل للحفظ.`;}

function updateHistoryButtons(){undoBtn.disabled=!edits.length;redoBtn.disabled=!redoStack.length;}
undoBtn.onclick=async()=>{if(!edits.length)return;redoStack.push(edits.pop());await rebuildWorking();updateHistoryButtons();await renderPage();};redoBtn.onclick=async()=>{if(!redoStack.length)return;edits.push(redoStack.pop());await rebuildWorking();updateHistoryButtons();await renderPage();};
zoomInBtn.onclick=()=>setZoom(zoom+.25);zoomOutBtn.onclick=()=>setZoom(zoom-.25);zoomLabel.onclick=()=>setZoom(1);fitBtn.onclick=()=>{fitWidth();void renderPage()};
function setZoom(v){zoom=clamp(Math.round(v*4)/4,.5,4);void renderPage();}
function fitWidth(){if(!workingDoc)return;let p=null;try{p=workingDoc.loadPage(pageIndex);const b=p.getBounds(),avail=Math.max(400,viewer.clientWidth-70);zoom=clamp(avail/(b[2]-b[0]),.5,2);}finally{try{p?.destroy?.()}catch{}}}

async function renderThumbnails(){thumbs.innerHTML='';for(let i=0;i<pageCount;i++){const card=document.createElement('button');card.className='thumb';const c=document.createElement('canvas'),s=document.createElement('span');s.textContent=String(i+1);card.append(c,s);card.onclick=async()=>{pageIndex=i;fitWidth();await renderPage()};thumbs.appendChild(card);setTimeout(()=>renderThumb(i,c),i*20);}}
async function renderThumb(i,c){let p=null,pix=null;try{p=workingDoc.loadPage(i);const b=p.getBounds(),sc=130/(b[2]-b[0]);pix=p.toPixmap(mupdf.Matrix.scale(sc,sc),mupdf.ColorSpace.DeviceRGB,false,true,'View','CropBox');const bmp=await createImageBitmap(new Blob([pix.asPNG()],{type:'image/png'}));c.width=bmp.width;c.height=bmp.height;c.getContext('2d').drawImage(bmp,0,0);bmp.close();}catch{}finally{try{pix?.destroy?.()}catch{}try{p?.destroy?.()}catch{}}}

saveBtn.onclick=async()=>{await closeEditor(true);if(!workingBytes)return;saveBtn.disabled=true;saveState.textContent='جاري الحفظ…';try{const suggested=sourceName.replace(/\.pdf$/i,'')+'-edited.pdf';if('showSaveFilePicker'in window){const h=await window.showSaveFilePicker({suggestedName:suggested,types:[{description:'PDF',accept:{'application/pdf':['.pdf']}}]});const w=await h.createWritable();await w.write(workingBytes);await w.close();saveState.textContent='تم حفظ الملف ✓';}else{const url=URL.createObjectURL(new Blob([workingBytes],{type:'application/pdf'})),a=document.createElement('a');a.href=url;a.download=suggested;a.click();setTimeout(()=>URL.revokeObjectURL(url),3000);saveState.textContent='تم تنزيل الملف ✓';}}catch(e){if(e?.name==='AbortError')saveState.textContent='تم إلغاء الحفظ.';else{console.error(e);saveState.textContent='خطأ في الحفظ: '+(e.message||e);}}finally{saveBtn.disabled=false;}};
window.addEventListener('resize',()=>{if(workingDoc){fitWidth();void renderPage()}});window.addEventListener('pagehide',destroyDocs);